### ISSUE TITLE
Feature: Add a --version option to the cli

### ISSUE THREAD

**Issue by swaranga** [dloomorg/dloom#1]
This needs to be consistent with the version we release with tags. So will need to do this via build variables

```yaml
name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.24.1'

    - name: Get version from tag
      id: vars
      run: echo ::set-output name=version::${GITHUB_REF##*/}

    - name: Build
      run: |
        go build -ldflags "-X main.Version=${{ steps.vars.outputs.version }}" -o yourappname

    - name: Upload binary
      uses: actions/upload-artifact@v2
      with:
        name: yourappname
        path: yourappname
```

And in the dloom.go:

```go
package main

import (
    "flag"
    "fmt"
    "os"
)

// Version will be set at build time
var Version = "dev"

func main() {
    versionFlag := flag.Bool("version", false, "Print the version and exit")
    flag.Parse()

    if *versionFlag {
        fmt.Println("Version:", Version)
        os.Exit(0)
    }

    // Your application logic here...
}
```
